[[redirects]]
  from = "/__/auth/*"
  to = "https://budget-tracker-23666.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"
